# ????
server.port=8080

# 允许循环依赖
spring.main.allow-circular-references=true

# RabbitMQ??
rabbitmq.host=localhost
rabbitmq.username=guest
rabbitmq.password=guest

logging.level.org.apache.kafka=ERROR
logging.level.kafka=ERROR
logging.level.org.apache.kafka.clients=ERROR
